### ISSUE TITLE
GenerationMixin._prepare_cache_for_generation() takes 6 positional arguments but 7 were given

### ISSUE THREAD

**Issue by Adudeguyman** [wildminder/ComfyUI-VibeVoice#3]
Looking forward to trying this out, but I got the error in the title when generating. Terminal output-

> # ComfyUI Error Report
## Error Details
- **Node ID:** 1
- **Node Type:** VibeVoiceTTS
- **Exception Type:** TypeError
- **Exception Message:** GenerationMixin._prepare_cache_for_generation() takes 6 positional arguments but 7 were given

## Stack Trace
```
  File "/home/ace/SD/ComfyUI/execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/ace/SD/ComfyUI/execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/ace/SD/ComfyUI/custom_nodes/comfyui-lora-manager/py/metadata_collector/metadata_hook.py", line 165, in async_map_node_over_list_with_metadata
    results = await original_map_node_over_list(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/ace/SD/ComfyUI/execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)

  File "/home/ace/SD/ComfyUI/execution.py", line 277, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^

  File "/home/ace/SD/ComfyUI/custom_nodes/ComfyUI-VibeVoice/vibevoice_nodes.py", line 281, in generate_audio
    outputs = model.generate(
              ^^^^^^^^^^^^^^^

  File "/home/ace/anaconda3/envs/comfy/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^

  File "/home/ace/SD/ComfyUI/custom_nodes/ComfyUI-VibeVoice/vibevoice/modular/modeling_vibevoice_inference.py", line 373, in generate
    generation_config, model_kwargs, input_ids, logits_processor, stopping_criteria = self._build_generate_config_model_kwargs(
                                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/ace/SD/ComfyUI/custom_nodes/ComfyUI-VibeVoice/vibevoice/modular/modeling_vibevoice_inference.py", line 303, in _build_generate_config_model_kwargs
    self._prepare_cache_for_generation(generation_config, model_kwargs, None, batch_size, max_cache_length, device)

**Comment by wildminder** [comment]
Can you provide more info about your environment or steps to reproduce this error? I’ve checked across different ComfyUI instances and haven’t experienced this issue.

**Comment by Adudeguyman** [comment]
Sure, running on Linux Mint with Cuda 12.9 on a 5090. Did a full comfy and torch update. Pip list compared to the requirements.txt-

> torch                             2.9.0.dev20250712+cu129
> torch-stoi                        0.2.3
> torchaudio                        2.8.0.dev20250713+cu129
> torchdiffeq                       0.2.5
> torchmetrics                      1.7.1
> torchscale                        0.3.0
> torchsde                          0.2.6
> torchvision                       0.24.0.dev20250713+cu129
> librosa                           0.10.2
> accelerate                        1.9.0
> numpy                             1.26.4
> huggingface-hub                   0.34.4
> einops                            0.8.1
> scipy                             1.15.2
> tokenizers                        0.21.4
> soundfile                         0.13.1
> s3tokenizer                       0.1.7
> conformer                         0.3.2
> safetensors                       0.5.3
> transformers                      4.56.0.dev0
> diffusers                         0.35.0
> tqdm                              4.67.1

**Comment by wildminder** [comment]
It seems the problem is with the latest Torch 2.9.0. I haven't tested the node with the nightly torch, only with the stable 2.8 version. I'll check with 2.9 asap

**Comment by wildminder** [comment]
This issue has been resolved with the latest node update. Tested with transformer 4.56 and 4.51

**Comment by zpengcom** [comment]
Haven't updated yet? It's still a problem with transformers 
ComfyUI-VibeVoice module for custom nodes: cannot import name 'BaseStreamer' from 'transformers.generation
